artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  s3_bucket: nlpsummarizer
  s3_object_key: dataset/samsum_dataset.csv
  local_data_file: samsum_dataset.csv

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: samsum_dataset.csv